### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Moogie237** [robhagemans/monobit#22]
Hello, I installed this to try to convert some Japanese FONTX files. When I typed "monobit-convert --help" in my terminal, I got a long python error message. Here it is in full:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/monobit-convert", line 5, in <module>
    from monobit.scripts.convert import main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/monobit/__init__.py", line 12, in <module>
    from .pack import Pack, operations as _pack_operations
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/monobit/pack.py", line 10, in <module>
    from .font import Font, FontProperties
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/monobit/font.py", line 14, in <module>
    from .glyph import Glyph
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/monobit/glyph.py", line 11, in <module>
    from .encoding import is_graphical, is_blank
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/monobit/encoding.py", line 1346, in <module>
    for _file in files('monobit.charmaps.freedos').iterdir():
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I get the same error when I type "monobit-banner --help" too.
I'm running on a Mid-2014 Macbook Pro with MacOS Catalina 10.15.7

**Comment by robhagemans** [comment]
That's really weird, that doesn't happen on my side (Linux install) so I can't really debug it. From the traceback it appears to be an issue in Python's own importlib. How was Python installed on that Mac and which version is it?

**Comment by robhagemans** [comment]
Seems to happen in Python 3.9 only (3.10 and 3.11 work fine). It is still odd, `importlib.resources` is supposed to work for Python 3.9

**Comment by robhagemans** [comment]
OK, I've got a fix that works for me locally on python 3.9. I'll update the release later today

**Comment by robhagemans** [comment]
Fixed with commit `dda80e1`. For reference, the issue was that Python 3.9 requires a `__init__.py` file in every directory travered by `files(...).iterdir()`, whereas 3.10 and above do not.

Thanks for reporting!

**Comment by Moogie237** [comment]
Thanks! I just installed python 3.10, seems to work for me there.
